version: '3.8'
services:
  data-ingestor:
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
    command: node --experimental-import-meta-resolve src/js/core/services/data/polygon-realtime.mjs

  ml-trainer:
    image: python:3.11-slim
    volumes:
      - ./src/py:/app/py
      - ./data:/app/data
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    command: python -m ml_core.training.trainer

  historical-fetcher:
    image: historical-fetcher:latest
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
    build: .
    environment:
      - PYTHONPATH=/app/src/py
    command: >
      bash -c "python -m data_ingestion.historical_data_fetcher $$@"
    volumes:
      - ./src/py:/app/src/py
      - ./data:/app/data
      
  training-cluster:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    command: >
      bash -c "python -m ml_core.training.trainer
      && aws s3 cp best_model.h5 s3://quant-trader-data-gintoki/models/"
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
