name: CI Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm test
      
      - uses: actions/setup-python@v4
      - run: pip install -r requirements.txt
      - run: pytest tests/py/
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports: ['6379:6379']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          npm install
          pip install -r requirements.txt
          npm test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          PYTHONPATH: "./src/py:./venv/lib/python3.11/site-packages"